### ISSUE TITLE
Use on existing server

### ISSUE THREAD

**Issue by manix** [MDSLab/wstun#14]
I already have a WS application server with quite some functionality, is there a way I could use the same server for wstun?

**Comment by npeditto** [comment]
I don't think so, because it self exposes a ws server.

**Comment by animaonline** [comment]
@manix how did you solve this problem? :)

**Comment by manix** [comment]
@animaonline I probably didn't, don't remember really. Looking at it now, and the comment above, I suppose the easiest way would be to just open a separate server using wstun.

**Comment by animaonline** [comment]
Thanks for replying!
